In [2]:
import tensorflow as tf

In [9]:
y_hat = tf.constant(36,name='y_hat')
y= tf.constant(45,name='y')


mul = tf.Variable(tf.multiply(y_hat,y),name="loss")

init = tf.global_variables_initializer()

print(mul)

<tf.Variable 'loss_1:0' shape=() dtype=int32_ref>


In [11]:
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(mul))

1620


In [16]:
a = tf.placeholder(tf.float32,name="a")
b = tf.placeholder(tf.float32,name = "b")

with tf.Session() as sess:
    print(sess.run(tf.multiply(a,b),feed_dict = {a:3.0,b:4.0}))

12.0


In [20]:
import numpy as np
X = tf.constant(np.random.randn(4,3)*0.01,name="X")
W = tf.constant(np.random.randn(4,4)*0.01,name="W")
B = tf.constant(np.random.randn(4,1)*0.01,name="B")

Y_hat = tf.Variable(tf.add(tf.matmul(W,X),B),name="Y_hat")

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(Y_hat))

[[ 0.00405281  0.00398442  0.00391634]
 [-0.00860179 -0.00866495 -0.00868329]
 [ 0.0047545   0.0045586   0.00448803]
 [-0.00343481 -0.00323258 -0.00317659]]
